# Generated by Django 6.0.5 on 2026-09-11 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KAOPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], default='RUNNING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_fetched', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaop_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('source', models.CharField(choices=[('KAOP', 'KAOP'), ('MANUAL', 'Manual'), ('SAT', 'Satellite'), ('OTHER', 'Other')], default='KAOP', max_length=10)),
                ('sub_county', models.CharField(blank=True, max_length=64)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude_m', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_stations', to='farmers.county')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temp_min_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_max_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_speed_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('solar_rad_mj', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('evapotranspiration_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quality', models.CharField(choices=[('RAW', 'Raw'), ('QC', 'QC Passed'), ('QCF', 'QC Failed'), ('IMP', 'Imputed')], default='RAW', max_length=4)),
                ('source_payload', models.JSONField(blank=True, help_text='Raw KAOP payload for audit.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='climate.weatherstation')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(db_index=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('horizon', models.CharField(choices=[('D1', '1 day'), ('D3', '3 days'), ('D7', '7 days'), ('D14', '14 days'), ('SEAS', 'Seasonal')], max_length=6)),
                ('expected_rainfall_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('expected_temp_min_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expected_temp_max_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('probability_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='climate.weatherstation')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ClimateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DROUGHT', 'Drought'), ('FLOOD', 'Flood'), ('PEST', 'Pest Outbreak'), ('HEAT', 'Heat Stress'), ('FROST', 'Frost')], db_index=True, max_length=8)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WATCH', 'Watch'), ('WARN', 'Warning'), ('EMERG', 'Emergency')], default='WATCH', max_length=6)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=8)),
                ('sub_county', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommended_action', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('affected_farms', models.ManyToManyField(blank=True, related_name='climate_alerts', to='farmers.farm')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climate_alerts', to='farmers.county')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climate_alerts_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['kind', 'status'], name='climate_cli_kind_8931f3_idx'), models.Index(fields=['county'], name='climate_cli_county__1eb4da_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='weatherstation',
            index=models.Index(fields=['county'], name='climate_wea_county__896e17_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherrecord',
            index=models.Index(fields=['station', 'date'], name='climate_wea_station_d46edb_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherrecord',
            index=models.Index(fields=['date'], name='climate_wea_date_83fa6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weatherrecord',
            unique_together={('station', 'date')},
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['station', 'horizon'], name='climate_for_station_0c976a_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['valid_from', 'valid_to'], name='climate_for_valid_f_3884de_idx'),
        ),
    ]
