# Generated by Django 6.0.5 on 2026-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('EXT_OFFICER', 'Extension Officer'), ('RESEARCHER', 'Researcher'), ('KALRO_ADMIN', 'KALRO Admin'), ('SYS_ADMIN', 'System Administrator')], db_index=True, default='FARMER', help_text='Determines dashboard & permissions.', max_length=20),
        ),
    ]
