# Generated by Django 6.0.5 on 2026-09-11 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('KAOP', 'KAOP (Weather)'), ('AGDATA', 'AgData Hub (Soil & Market)'), ('SELECTOR', 'Selector Platform'), ('ISHAMBA', 'iShamba SMS'), ('REGISTRY', 'KALRO Farmer Registry'), ('OTHER', 'Other')], max_length=10, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('direction', models.CharField(choices=[('IN', 'Inbound (pull)'), ('OUT', 'Outbound (push)'), ('BOTH', 'Bidirectional')], default='BOTH', max_length=6)),
                ('base_url', models.URLField(blank=True)),
                ('auth_type', models.CharField(choices=[('NONE', 'None'), ('APIKEY', 'API Key'), ('BEARER', 'Bearer Token'), ('BASIC', 'Basic Auth'), ('OAUTH2', 'OAuth 2.0')], default='APIKEY', max_length=8)),
                ('api_key', models.CharField(blank=True, max_length=256)),
                ('api_secret', models.CharField(blank=True, max_length=256)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('bearer_token', models.TextField(blank=True)),
                ('oauth_token_url', models.URLField(blank=True)),
                ('extra_headers', models.JSONField(blank=True, default=dict)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration configuration',
                'verbose_name_plural': 'Integration configurations',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('KAOP', 'KAOP (Weather)'), ('AGDATA', 'AgData Hub (Soil & Market)'), ('SELECTOR', 'Selector Platform'), ('ISHAMBA', 'iShamba SMS'), ('REGISTRY', 'KALRO Farmer Registry'), ('OTHER', 'Other')], max_length=10)),
                ('operation', models.CharField(choices=[('PULL_WEATHER', 'Pull Weather (KAOP)'), ('PULL_FORECAST', 'Pull Forecast (KAOP)'), ('PULL_SOIL', 'Pull Soil (AgData)'), ('PULL_MARKET', 'Pull Market Prices (AgData)'), ('PULL_REGISTRY', 'Pull Farmer Registry'), ('PUSH_SMS', 'Push SMS (iShamba)'), ('PUSH_SELECTOR', 'Push to Selector'), ('HEALTH', 'Health Check'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=8)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('response_snippet', models.TextField(blank=True)),
                ('records_fetched', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='integrations.integrationconfig')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('KAOP', 'KAOP (Weather)'), ('AGDATA', 'AgData Hub (Soil & Market)'), ('SELECTOR', 'Selector Platform'), ('ISHAMBA', 'iShamba SMS'), ('REGISTRY', 'KALRO Farmer Registry'), ('OTHER', 'Other')], max_length=10)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('FAILED', 'Failed')], default='RECEIVED', max_length=10)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('signature_verified', models.BooleanField(default=False)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True)),
                ('related_sync_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='integrations.synclog')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['provider', 'operation'], name='integration_provide_9efad8_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status'], name='integration_status_bf366b_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['provider', 'event_type'], name='integration_provide_1db1db_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status'], name='integration_status_c4bc1e_idx'),
        ),
    ]
