# Generated by Django 6.0.5 on 2026-09-11 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('objective', models.TextField(blank=True)),
                ('season', models.CharField(blank=True, help_text='e.g. 2025 LR (Long Rains).', max_length=32)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('DONE', 'Completed'), ('SUSP', 'Suspended'), ('ABAND', 'Abandoned')], default='PLANNED', max_length=8)),
                ('design', models.CharField(choices=[('RCBD', 'Randomized Complete Block Design'), ('CRD', 'Completely Randomized Design'), ('SPLIT', 'Split-plot'), ('FACT', 'Factorial'), ('DEMO', 'Demonstration'), ('OTHER', 'Other')], default='RCBD', max_length=6)),
                ('replications', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_on', models.DateField(blank=True, db_index=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Published trials contribute to the 150K fertilizer database.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trials', to='farmers.county')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trials', to='crops.crop')),
                ('lead_researcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_trials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrialImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='trial_imports/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trial', models.ForeignKey(blank=True, help_text='Optional — leave blank if the CSV specifies trial codes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='trials.trial')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrialSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('site_type', models.CharField(choices=[('KALRO', 'KALRO Research Center'), ('AGRIPARK', 'AgriPark'), ('FARMER', "Farmer's Field"), ('SCHOOL', 'School / Institution'), ('OTHER', 'Other')], default='KALRO', max_length=10)),
                ('sub_county', models.CharField(blank=True, max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude_m', models.PositiveIntegerField(blank=True, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=64)),
                ('agro_ecological_zone', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_sites', to='farmers.county')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='trial',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trials', to='trials.trialsite'),
        ),
        migrations.CreateModel(
            name='TrialTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('fertilizer_type', models.CharField(blank=True, max_length=64)),
                ('n_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('p_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('k_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('organic_amendment', models.CharField(blank=True, max_length=128)),
                ('is_control', models.BooleanField(default=False)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='trials.trial')),
            ],
            options={
                'ordering': ['trial', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TrialResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(blank=True, max_length=16)),
                ('replication', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observed_on', models.DateField(db_index=True)),
                ('plant_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('biomass_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grain_yield_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_yield_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('soil_n_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('soil_p_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('soil_k_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('nitrogen_use_efficiency', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source_row', models.JSONField(blank=True, help_text='Original row from imported CSV.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='trials.trialtreatment')),
            ],
            options={
                'ordering': ['-observed_on'],
            },
        ),
        migrations.AddIndex(
            model_name='trialsite',
            index=models.Index(fields=['county', 'site_type'], name='trials_tria_county__169635_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['status'], name='trials_tria_status_e769d3_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['crop', 'season'], name='trials_tria_crop_id_62adb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trialtreatment',
            unique_together={('trial', 'code')},
        ),
        migrations.AddIndex(
            model_name='trialresult',
            index=models.Index(fields=['treatment', 'observed_on'], name='trials_tria_treatme_58fff4_idx'),
        ),
        migrations.AddIndex(
            model_name='trialresult',
            index=models.Index(fields=['observed_on'], name='trials_tria_observe_657cf0_idx'),
        ),
    ]
