# Generated by Django 6.0.5 on 2026-09-11 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_agripark', models.BooleanField(default=False, help_text='Whether KALRO operates an AgriPark in this county.')),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('alt_phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sub_county', models.CharField(blank=True, max_length=64)),
                ('ward', models.CharField(blank=True, max_length=64)),
                ('village', models.CharField(blank=True, max_length=64)),
                ('total_land_size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('land_size_unit', models.CharField(choices=[('ACRE', 'Acres'), ('HA', 'Hectares')], default='ACRE', max_length=6)),
                ('primary_enterprise', models.CharField(blank=True, help_text='e.g. Maize, Dairy, Horticulture.', max_length=64)),
                ('registration_source', models.CharField(default='KALRO', help_text='KALRO, Extension Officer, Self, Bulk import, etc.', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='farmers.county')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_farmers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size_unit', models.CharField(choices=[('ACRE', 'Acres'), ('HA', 'Hectares')], default='ACRE', max_length=6)),
                ('sub_county', models.CharField(blank=True, max_length=64)),
                ('ward', models.CharField(blank=True, max_length=64)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude_m', models.PositiveIntegerField(blank=True, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=64)),
                ('irrigation_type', models.CharField(choices=[('RAIN', 'Rain-fed'), ('DRIP', 'Drip'), ('SPRINK', 'Sprinkler'), ('FURROW', 'Furrow'), ('MIXED', 'Mixed'), ('NONE', 'None')], default='RAIN', max_length=6)),
                ('is_agripark_demo', models.BooleanField(default=False, help_text='Farm used as an AgriPark demo site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='farmers.county')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farmers.farmer')),
            ],
            options={
                'ordering': ['farmer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FarmerImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='farmer_imports/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partially Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['county', 'sub_county'], name='farmers_far_county__1c7ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['phone_number'], name='farmers_far_phone_n_3a2c24_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['national_id'], name='farmers_far_nationa_6f4828_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['farmer'], name='farmers_far_farmer__491730_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['county'], name='farmers_far_county__d0abe4_idx'),
        ),
    ]
