# Generated by Django 6.0.5 on 2026-09-11 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgDataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], default='RUNNING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('soil_records_fetched', models.PositiveIntegerField(default=0)),
                ('price_records_fetched', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agdata_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NutrientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('soil_texture', models.CharField(blank=True, max_length=64)),
                ('ph_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ph_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('n_min_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('n_max_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('p_min_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p_max_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('k_min_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('k_max_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_profiles', to='crops.crop')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('MAIZE', 'Maize'), ('BEANS', 'Beans'), ('RICE', 'Rice'), ('WHEAT', 'Wheat'), ('SORGHUM', 'Sorghum'), ('MILLET', 'Millet'), ('POTATO', 'Potato'), ('TOMATO', 'Tomato'), ('KALE', 'Kale'), ('CABBAGE', 'Cabbage'), ('DAP', 'DAP Fertilizer'), ('CAN', 'CAN Fertilizer'), ('UREA', 'Urea'), ('OTHER', 'Other')], db_index=True, max_length=10)),
                ('commodity_label', models.CharField(blank=True, help_text="Free-text if 'Other'.", max_length=64)),
                ('market_name', models.CharField(blank=True, max_length=128)),
                ('price_ksh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='KES/kg', max_length=32)),
                ('observed_on', models.DateField(db_index=True)),
                ('source', models.CharField(default='AgData Hub', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_prices', to='farmers.county')),
            ],
            options={
                'ordering': ['-observed_on'],
                'indexes': [models.Index(fields=['commodity', 'observed_on'], name='soil_market_commodi_910496_idx'), models.Index(fields=['county', 'observed_on'], name='soil_market_county__bc6489_idx')],
            },
        ),
        migrations.CreateModel(
            name='SoilTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sampled_on', models.DateField(db_index=True)),
                ('lab', models.CharField(choices=[('KALRO', 'KALRO'), ('KEPHIS', 'KEPHIS'), ('PRIVATE', 'Private Lab'), ('FIELD', 'Field Test Kit'), ('OTHER', 'Other')], default='KALRO', max_length=10)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('organic_carbon_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('nitrogen_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('phosphorus_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('potassium_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calcium_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('magnesium_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sulfur_ppm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('zinc_ppm', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('boron_ppm', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('iron_ppm', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('texture', models.CharField(blank=True, max_length=64)),
                ('bulk_density', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moisture_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cec_meq', models.DecimalField(blank=True, decimal_places=2, help_text='Cation Exchange Capacity (meq/100g)', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, help_text='Original AgData Hub payload.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_tests', to='farmers.farm')),
                ('sampled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soil_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sampled_on'],
                'indexes': [models.Index(fields=['farm', 'sampled_on'], name='soil_soilte_farm_id_ddfb5c_idx'), models.Index(fields=['sample_id'], name='soil_soilte_sample__c18eca_idx')],
            },
        ),
    ]
