# Generated by Django 6.0.5 on 2026-09-11 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('farmers', '0001_initial'),
        ('pinn_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PLANTING', 'Planting'), ('FERT', 'Fertilizer'), ('IRRIG', 'Irrigation'), ('PEST', 'Pest Management'), ('DISEASE', 'Disease Management'), ('WEATHER', 'Weather Warning'), ('HARVEST', 'Harvest'), ('MARKET', 'Market'), ('GEN', 'General')], db_index=True, max_length=10)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=6)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCEL', 'Cancelled')], default='DRAFT', max_length=10)),
                ('source', models.CharField(choices=[('PINN', 'PINN Engine'), ('MANUAL', 'Manual'), ('RULE', 'Rule-based'), ('KALRO', 'KALRO Bulletin')], default='PINN', max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Farmer-facing message.')),
                ('short_message', models.CharField(blank=True, help_text='SMS-friendly text (≤ 320 chars).', max_length=320)),
                ('explanation', models.TextField(blank=True, help_text='Human-readable reasoning for the recommendation.')),
                ('explanation_factors', models.JSONField(blank=True, default=list, help_text="Ordered list of contributing factors, e.g. [{'name': 'rainfall', 'weight': 0.4}, ...]")),
                ('physics_residuals', models.JSONField(blank=True, default=dict, help_text='Copy of inference physics residuals for auditing.')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories_created', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories', to='crops.crop')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='farmers.farm')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='farmers.farmer')),
                ('growth_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories', to='crops.growthstage')),
                ('inference_run', models.ForeignKey(blank=True, help_text='The PINN inference that produced this advisory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories', to='pinn_engine.inferencerun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisoryDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'iShamba SMS'), ('SELECTOR', 'Selector Platform'), ('EMAIL', 'Email'), ('USSD', 'USSD'), ('MANUAL', 'Manual / Verbal')], max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='QUEUED', max_length=10)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_ref', models.CharField(blank=True, help_text='Selector ID / email / etc.', max_length=128)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_text', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('advisory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='advisories.advisory')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisoryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, choices=[('1', 'Very Poor'), ('2', 'Poor'), ('3', 'Neutral'), ('4', 'Good'), ('5', 'Very Good')], max_length=2)),
                ('outcome', models.CharField(choices=[('FOLLOWED', 'Followed advice'), ('PARTIAL', 'Partially followed'), ('NOT', 'Did not follow'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('advisory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='advisories.advisory')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.AddIndex(
            model_name='advisory',
            index=models.Index(fields=['status', 'priority'], name='advisories__status_8b2436_idx'),
        ),
        migrations.AddIndex(
            model_name='advisory',
            index=models.Index(fields=['kind'], name='advisories__kind_1c323d_idx'),
        ),
        migrations.AddIndex(
            model_name='advisory',
            index=models.Index(fields=['farmer', 'created_at'], name='advisories__farmer__251e27_idx'),
        ),
        migrations.AddIndex(
            model_name='advisory',
            index=models.Index(fields=['farm', 'crop'], name='advisories__farm_id_f4a09e_idx'),
        ),
        migrations.AddIndex(
            model_name='advisorydelivery',
            index=models.Index(fields=['advisory', 'channel'], name='advisories__advisor_d665cf_idx'),
        ),
        migrations.AddIndex(
            model_name='advisorydelivery',
            index=models.Index(fields=['status'], name='advisories__status_41505e_idx'),
        ),
        migrations.AddIndex(
            model_name='advisoryfeedback',
            index=models.Index(fields=['advisory', 'rating'], name='advisories__advisor_14dd0f_idx'),
        ),
    ]
