# Generated by Django 6.0.5 on 2026-09-11 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Crop categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=128)),
                ('code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('season', models.CharField(choices=[('LR', 'Long Rains (Mar–May)'), ('SR', 'Short Rains (Oct–Dec)'), ('BOTH', 'Both seasons'), ('DRY', 'Dry season / irrigated'), ('PER', 'Perennial')], default='BOTH', max_length=6)),
                ('growth_habit', models.CharField(choices=[('ANN', 'Annual'), ('BIE', 'Biennial'), ('PER', 'Perennial')], default='ANN', max_length=4)),
                ('optimal_ph_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('optimal_ph_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('water_requirement_mm', models.PositiveIntegerField(blank=True, help_text='Seasonal crop water requirement (mm).', null=True)),
                ('n_requirement_kg_ha', models.DecimalField(blank=True, decimal_places=2, help_text='Nitrogen requirement kg/ha.', max_digits=6, null=True)),
                ('p_requirement_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('k_requirement_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('base_temp_c', models.DecimalField(blank=True, decimal_places=2, help_text='Base temperature for growing degree day calculations.', max_digits=5, null=True)),
                ('max_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('days_to_maturity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expected_yield_kg_ha', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='crops.cropcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('start_day', models.PositiveSmallIntegerField(help_text='Days after planting.')),
                ('end_day', models.PositiveSmallIntegerField(help_text='Days after planting.')),
                ('kc_coefficient', models.DecimalField(blank=True, decimal_places=2, help_text='Crop coefficient for evapotranspiration (FAO-56).', max_digits=4, null=True)),
                ('water_requirement_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('n_requirement_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('p_requirement_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('k_requirement_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('critical_notes', models.TextField(blank=True, help_text='Stage-specific warnings (e.g. water stress sensitive).')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_stages', to='crops.crop')),
            ],
            options={
                'ordering': ['crop', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aez', models.CharField(blank=True, choices=[('HL', 'Highland'), ('ML', 'Midland'), ('LL', 'Lowland'), ('ARID', 'Arid / Semi-arid')], max_length=4)),
                ('planting_start_month', models.PositiveSmallIntegerField(help_text='1–12')),
                ('planting_end_month', models.PositiveSmallIntegerField(help_text='1–12')),
                ('harvest_start_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('harvest_end_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expected_rainfall_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_calendars', to='farmers.county')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='crops.crop')),
            ],
            options={
                'ordering': ['crop', 'county'],
                'indexes': [models.Index(fields=['crop', 'county'], name='crops_cropc_crop_id_f3a3b5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['category'], name='crops_crop_categor_6e3079_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['season'], name='crops_crop_season_c259d7_idx'),
        ),
        migrations.AddIndex(
            model_name='growthstage',
            index=models.Index(fields=['crop', 'order'], name='crops_growt_crop_id_16b8fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='growthstage',
            unique_together={('crop', 'name')},
        ),
    ]
