# Generated by Django 6.0.5 on 2026-09-11 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('WATER', 'Water Balance'), ('NUTRIENT', 'Nutrient Cycling'), ('ENERGY', 'Energy Conservation'), ('CARBON', 'Carbon Balance'), ('MASS', 'Mass Conservation'), ('CUSTOM', 'Custom')], max_length=10)),
                ('domain', models.CharField(choices=[('SOIL', 'Soil'), ('PLANT', 'Plant'), ('ATM', 'Atmosphere'), ('COMB', 'Combined')], default='COMB', max_length=6)),
                ('description', models.TextField()),
                ('mathematical_form', models.TextField(help_text='LaTeX or plain equation, e.g. dS/dt = P - ET - R - D')),
                ('weight', models.DecimalField(decimal_places=4, default=1.0, help_text='Weight in the composite loss: L = L_data + λ * L_physics.', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physics_constraints', to='crops.crop')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PINNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('version', models.CharField(default='0.1.0', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('architecture', models.CharField(choices=[('MLP', 'Feed-forward MLP'), ('LSTM', 'LSTM'), ('GRU', 'GRU'), ('TF', 'Transformer'), ('HYBRID', 'Hybrid')], default='MLP', max_length=10)),
                ('hidden_layers', models.JSONField(blank=True, default=list, help_text='e.g. [64, 64, 32]')),
                ('activation', models.CharField(default='tanh', max_length=16)),
                ('input_features', models.JSONField(blank=True, default=list, help_text='Ordered list of input feature names.')),
                ('output_targets', models.JSONField(blank=True, default=list, help_text='Ordered list of output targets (e.g. yield, N_uptake).')),
                ('physics_lambda', models.DecimalField(decimal_places=4, default=0.1, help_text='Global weight on the physics loss term.', max_digits=6)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('TRAINING', 'Training'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('artifact_path', models.CharField(blank=True, help_text='Path to saved weights file (.pt / .h5).', max_length=512)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Final metrics: rmse, r2, mae, physics_residual.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinn_models', to=settings.AUTH_USER_MODEL)),
                ('physics_constraints', models.ManyToManyField(blank=True, related_name='models', to='pinn_engine.physicsconstraint')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_label', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=10)),
                ('epochs', models.PositiveIntegerField(default=100)),
                ('batch_size', models.PositiveIntegerField(default=64)),
                ('learning_rate', models.DecimalField(decimal_places=6, default=0.001, max_digits=8)),
                ('train_split', models.DecimalField(decimal_places=2, default=0.8, max_digits=4)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('loss_history', models.JSONField(blank=True, default=list)),
                ('final_metrics', models.JSONField(blank=True, default=dict)),
                ('log_text', models.TextField(blank=True)),
                ('error_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='pinn_engine.pinnmodel')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinn_training_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.PositiveIntegerField(blank=True, null=True)),
                ('step', models.PositiveIntegerField(blank=True, null=True)),
                ('data_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('physics_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('total_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('rmse', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('mae', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('r2', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('physics_residual', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='pinn_engine.pinnmodel')),
                ('training_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='pinn_engine.trainingrun')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('feature_attributions', models.JSONField(blank=True, default=dict, help_text="e.g. {'rainfall': 0.42, 'soil_n': 0.31, ...}")),
                ('physics_residuals', models.JSONField(blank=True, default=dict, help_text='Residual per physics constraint — small = physically consistent.')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_runs', to='crops.crop')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_runs', to='farmers.farm')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinn_inferences', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_runs', to='pinn_engine.pinnmodel')),
                ('training_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inferences', to='pinn_engine.trainingrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='physicsconstraint',
            index=models.Index(fields=['kind', 'is_active'], name='pinn_engine_kind_28c49d_idx'),
        ),
        migrations.AddIndex(
            model_name='pinnmodel',
            index=models.Index(fields=['status'], name='pinn_engine_status_7c19f9_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrun',
            index=models.Index(fields=['model', 'status'], name='pinn_engine_model_i_3a4fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='modelmetric',
            index=models.Index(fields=['model', 'epoch'], name='pinn_engine_model_i_4aacfc_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['model', 'status'], name='pinn_engine_model_i_ce2b47_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['farm', 'crop'], name='pinn_engine_farm_id_64df55_idx'),
        ),
    ]
